name: Integration tests

on:
  push:
    branches:
      - integration-test-possible-fix

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [12, 14, 16, 18]
        os: [linux, windows]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Retrieve dependencies from cache
        id: cacheNpm
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-v${{ matrix.version }}-${{ matrix.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-v${{ matrix.version }}-${{ matrix.os }}-${{ github.ref }}-
            npm-v${{ matrix.version }}-${{ matrix.os }}-refs/heads/master-

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        if: steps.cacheNpm.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Compile
        run: npm run compile

      - name: Run integration tests
        run: npm run test:int -- -t deploy.* -d 'node${{ matrix.version }}-${{ matrix.os }}(-webpack)?'
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
